replicaCount: 1
persistence:
  enabled: true
  accessModes:
    - ReadWriteOnce
  size: 3Gi
  storageClass: "local-path"
smtp4dev:
  ServerOptions__BasePath: /
  ServerOptions__LockSettings: false
  ServerOptions__NumberOfMessagesToKeep: 500
  ServerOptions__NumberOfSessionsToKeep: 100
  ServerOptions__Hostname: c18540e8-0070-4fa2-96e4-0dc7f780c267-10-244-0-90-3100.spch.r.killercoda.com
ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: basic-auth
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required'
    nginx.ingress.kubernetes.io/auth-keepalive: "10"
    nginx.ingress.kubernetes.io/auth-keepalive-timeout: "60"
    kubernetes.io/tls-acme: "true"
  hosts:
  - host: c18540e8-0070-4fa2-96e4-0dc7f780c267-10-244-0-90-3100.spch.r.killercoda.com
    paths:
    - path: /
      pathType: ImplementationSpecific
  tls:
  - secretName: c18540e8-0070-4fa2-96e4-0dc7f780c267-10-244-0-90-3100.spch.r.killercoda.com
    hosts:
    - c18540e8-0070-4fa2-96e4-0dc7f780c267-10-244-0-90-3100.spch.r.killercoda.com
extraEnv:
- name: DOTNET_USE_POLLING_FILE_WATCHER
  value: "1"
- name: ServerOptions__AuthenticationRequired
  value: "false"
- name: ServerOptions__WebAuthenticationRequired
  value: "false"
- name: ServerOptions__Users__0__Username
  value: admin
- name: ServerOptions__Users__0__Password
  value: pass1234S3c
- name: ServerOptions__Users__0__DefaultMailbox
  value: Default